# TEST profile configuration
spring:
  config:
    activate:
      on-profile: test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: false

  kafka:
    listener:
      auto-startup: false

logging:
  level:
    org.fitlog: DEBUG
