spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}

jwt:
  token:
    signing_key: ${JWT_SIGNING_KEY}
    expiration: ${JWT_EXPIRATION}

server:
  servlet:
    context-path: /api/v1
  port: 8080

app:
  frontend:
    oauth2-redirect-uri: "http://localhost:5173/oauth2/redirect"

openai:
  api-key: ${OPENAI_API_KEY}

springdoc:
  packagesToScan: com.wteam.backend
